spring:
  profiles:
    active: local
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false
  freemarker:
    cache: false

  jwt:
    secret: govlepel@$&
#server:
#  port: 8081